version: '3.8'

services:
  facturx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facturx
    volumes:
      - /home/wegelin/facturx:/data
    restart: unless-stopped
